name: ecr-push-keycloak-theme
on:
  push:
    paths:
      - /**
      - .github/workflows/ecr-push-keycloak-theme.yml
permissions:
  id-token: write
  contents: read
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::911472739931:role/github
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-keycloak-theme
          restore-keys: |
            ${{ runner.os }}-buildx-keycloak-theme

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/keycloak_theme:latest-${{ github.ref_name }}
            ${{ steps.login-ecr.outputs.registry }}/keycloak_theme:commit-${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
